fix: ensure that dev modules are installed to prevent build failure
Ref:

-------------------------------------------------------

$ npm run build

> 11ty-base@1.0.0 build
> npx npm-run-all -s clean eleventy lint:css lint:js sass:build autoprefix:build js:build

Need to install the following packages:
  run
Ok to proceed? (y) y
Watching /Users/rwaldron/clonez/tm-landing and all sub-directories not excluded by your .gitignore. Will not monitor dotfiles.
Found & ignored ./node_modules ; is listed in .gitignore

Starting: clean
node:internal/modules/cjs/loader:943
  throw err;
  ^

Error: Cannot find module '/Users/rwaldron/clonez/tm-landing/clean'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.Module._load (node:internal/modules/cjs/loader:773:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
    at node:internal/main/run_main_module:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}